const SVG_COLOR_BLACK = '#111111';
const SVG_COLOR_WHITE = '#ffffff';
const SVG_COLOR_BLUE = '#0078d4';
const SVG_COLOR_GREEN = '#107c10';
const SVG_COLOR_ORANGE = '#ca5010';
const SVG_COLOR_PURPLE = '#5c2d91';
const SVG_ERROR = '#DC362E';
const SVG_INFO = '#555555';
const SVG_COLOR_GREY = '#777777';
const SVG_COLOR_YELLOW = '#ffb900';
const SVG_COLOR_PINK = '#e3008c';
const SVG_COLOR_TEAL = '#00aba9';
const SVG_COLOR_SKY = '#2E63FA';
const SVG_COLOR_GRASS = '#498205';
const SVG_COLOR_NAVY = '#2C74D6';
const SVG_COLOR_GREY_500 = '#667085';
const SVG_COLOR_GREY_850 = '#3b3b3b';
const SVG_COLOR_BLUE_500 = '#2196F3';
const SVG_GREY_ICON = '#98A2B3';

export {
  SVG_COLOR_BLACK,
  SVG_COLOR_BLUE,
  SVG_COLOR_GREEN,
  SVG_COLOR_SKY,
  SVG_COLOR_GRASS,
  SVG_COLOR_ORANGE,
  SVG_COLOR_PINK,
  SVG_COLOR_PURPLE,
  SVG_COLOR_TEAL,
  SVG_COLOR_YELLOW,
  SVG_COLOR_GREY,
  SVG_ERROR,
  SVG_INFO,
  SVG_COLOR_WHITE,
  SVG_COLOR_NAVY,
  SVG_COLOR_GREY_500,
  SVG_COLOR_GREY_850,
  SVG_COLOR_BLUE_500,
  SVG_GREY_ICON
};
